import argparse
import pathlib
import wave


TARGET_RATE = 8000


def read_wav(path):
    with wave.open(str(path), "rb") as wav_file:
        channels = wav_file.getnchannels()
        sample_width = wav_file.getsampwidth()
        sample_rate = wav_file.getframerate()
        frames = wav_file.readframes(wav_file.getnframes())

    if sample_width not in (1, 2):
        raise ValueError("Only 8-bit or 16-bit PCM WAV files are supported.")

    samples = []
    step = sample_width * channels
    for index in range(0, len(frames), step):
        channel_samples = []
        for channel in range(channels):
            offset = index + channel * sample_width
            if sample_width == 1:
                value = frames[offset] - 128
            else:
                value = int.from_bytes(frames[offset:offset + 2], "little", signed=True) // 256
            channel_samples.append(value)
        mono = sum(channel_samples) // len(channel_samples)
        samples.append(mono)

    return samples, sample_rate


def resample(samples, source_rate, target_rate):
    if source_rate == target_rate:
        return samples

    target_length = int(len(samples) * target_rate / source_rate)
    if target_length <= 0:
        return []

    output = []
    for index in range(target_length):
        source_index = index * source_rate / target_rate
        left = int(source_index)
        right = min(left + 1, len(samples) - 1)
        fraction = source_index - left
        value = int(samples[left] * (1 - fraction) + samples[right] * fraction)
        output.append(value)
    return output


def to_unsigned_8bit(samples):
    return bytes(max(0, min(255, sample + 128)) for sample in samples)


def write_python_module(path, data):
    chunks = []
    for index in range(0, len(data), 24):
        escaped = "".join(f"\\x{byte:02x}" for byte in data[index:index + 24])
        chunks.append(f"    b\"{escaped}\"")

    content = (
        "# Generated by wav_to_audio_sample.py. Do not edit manually.\n"
        f"SAMPLE_RATE = {TARGET_RATE}\n"
        "AUDIO_DATA = (\n"
        + "\n".join(chunks)
        + "\n)\n"
    )
    path.write_text(content, encoding="ascii")


def main():
    parser = argparse.ArgumentParser(description="Convert a short PCM WAV into a MicroPython audio_sample.py module.")
    parser.add_argument("wav_file", type=pathlib.Path)
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("audio_sample.py"))
    args = parser.parse_args()

    samples, sample_rate = read_wav(args.wav_file)
    samples = resample(samples, sample_rate, TARGET_RATE)
    data = to_unsigned_8bit(samples)
    write_python_module(args.output, data)
    print(f"Wrote {args.output} ({len(data)} bytes, {TARGET_RATE} Hz)")


if __name__ == "__main__":
    main()
